### PR TITLE
Make powervs_login more verbose

### PR DESCRIPTION
**Pull request by dpkshetty**
Currently only PowerVS service Id is printed which is alien to the end user. Printing both service name and Id will help user to relate better.

### CODE REVIEW

**Comment by dpkshetty** [comment]
@bpradipt would you know why the macos build is failing ? @mkumatag

**Comment by bpradipt** [comment]
@dpkshetty please rebase and squash the commits. This commit includes lots of other commits

**Comment by dpkshetty** [comment]
Hmm for some reason when I sent the PR it took devel as the base.. tho' I had intended master.. let me resend a fresh PR against master directly!

**Comment by dpkshetty** [comment]
I will close this.
Sent #121  instead against the master branch

**Pull request closed without merging**
