### PR TITLE
Add non-zero exit value for errors

### PR DESCRIPTION
**Pull request by rpsene**
Adds exit 1 in critical locations where the execution must fail and stop.

### CODE REVIEW

**Review by cs-zhang — CHANGES_REQUESTED** [review]
When looked at the error call, it calls exit at the end of the function. don't know why it did not exit with -1 or error code passed in. So we may not need to call `exit` again.

**Comment by yussufsh** [comment]
> When looked at the error call, it calls exit at the end of the function. don't know why it did not exit with -1 or error code passed in. So we may not need to call `exit` again.

Right, the error function will print the message and exit with -1 if no code is passed.

**Comment by rpsene** [comment]
@yussufsh @cs-zhang this approach is not working. Also, it is common to expect for 1 instead of -1 as error. Can we fix this?

**Comment by yussufsh** [comment]
@rpsene Wherever the error is called it will exit. We have tested this.

Usage of the codes are debatable. Have kept it default `-1`. Now depending on the error type we can send any code including `1`. It needs to be designed/classified and implemented.

**Comment by rpsene** [comment]
@yussufsh change the MTU of the host where you are running the script to a big number; try to run the automation. It will fail, and the execution will not get cancelled. This is one example where the current solution fails.

**Comment by bpradipt** [comment]
> @yussufsh @cs-zhang this approach is not working. Also, it is common to expect for 1 instead of -1 as error. Can we fix this?

This is a fair point. Usually a non-zero (1-255) exit status indicates failure [1]. So its better to change the exit code to `1` from `-1`  to follow established guidelines.

[1] https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html

**Comment by bpradipt** [comment]
The bigger question is why the `error` function is not behaving as expected - https://github.com/ocp-power-automation/openshift-install-power/blob/24e6df97d9927debadb1198cadda37bede853a29/openshift-install-powervs#L132-L138

@rpsene does the code hangs when you run the scenario mentioned in - https://github.com/ocp-power-automation/openshift-install-power/pull/163#issuecomment-856722845 ? And does the proposed PR fixes this issue ?

**Comment by bpradipt** [comment]
@rpsene @cs-zhang @yussufsh changing `ret_code=-1` statement to `ret_code=1` in https://github.com/ocp-power-automation/openshift-install-power/blob/24e6df97d9927debadb1198cadda37bede853a29/openshift-install-powervs#L132-L138 will take care of correct exit code in case of missing exit code.  
@rpsene can you try and see if it resolves the issues ?

**Comment by yussufsh** [comment]
With -1 or 1 it will exit the script. Not sure if that will solve the issue?

We need to work on classifying the return codes and assign them at proper places in a separate issue. Eg: variables, validation, execution, etc.

Can someone try the scenario that rpsene mentioned?

**Comment by rpsene** [comment]
There is 2 issues: 1 - set the commonly used return code when a failure happens so this script can be easily integrated with other solutions and 2 - the wrong MTU setting that kills the connection to the bastion and didn't crash the execution.

**Comment by bpradipt** [comment]
> There is 2 issues: 1 - set the commonly used return code when a failure happens so this script can be easily integrated with other solutions and 2 - the wrong MTU setting that kills the connection to the bastion and didn't crash the execution.

@rpsene the change mentioned in https://github.com/ocp-power-automation/openshift-install-power/pull/163#issuecomment-857372624 should fix the return code issue. Can you please update your PR accordingly.

**Comment by bpradipt** [comment]
Superseded by the following PR - https://github.com/ocp-power-automation/openshift-install-power/pull/170

**Pull request closed without merging**
