### PR TITLE
Remove cygwin workflow

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot Parab <Prajyot.Parab1@ibm.com>

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by yussufsh — APPROVED** [review]
/approve

**Comment by yussufsh** [comment]
@mkumatag is labels plugin part of this project?

**Comment by mkumatag** [comment]
> @mkumatag is labels plugin part of this project?

There is `OWNERS` file missing in this repo, can you create one to add the approval tag?

**Pull request merged**
