### PR TITLE
Updated expression as per curl output

### PR DESCRIPTION
**Pull request by sajauddin**
Modified the expression as per the change in the output of curl command for fetching ALL_OCP_VERSIONS.

### CODE REVIEW

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
/hold

The curl command still does not give any o/p on GitBash/Cygwin for Windows for me. Please check.

**Comment by yussufsh** [comment]
@sajauddin I am also seeing other versions when we grep the RELEASE_VER=4.9. See below for example it is showing ` 4.4.9` as well.

```
GMX+AVRSAF744@DESKTOP-KS58TIV MINGW64 ~
$ ALL_OCP_VERSIONS=$(curl -skL https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp/| grep "$RELEASE_VER" | cut -f2 -d '>' | cut -f1 -d '<' | tac)

GMX+AVRSAF744@DESKTOP-KS58TIV MINGW64 ~
$ echo $ALL_OCP_VERSIONS
stable-4.9 latest-4.9 fast-4.9 candidate-4.9 4.9.9 4.9.8 4.9.7 4.9.6 4.9.5 4.9.4 4.9.3 4.9.2 4.9.12 4.9.11 4.9.10 4.9.1 4.9.0 4.9.0-rc.8 4.9.0-rc.7 4.9.0-rc.6 4.9.0-rc.5 4.9.0-rc.4 4.9.0-rc.2 4.9.0-rc.1 4.9.0-rc.0 4.4.9

```

**Comment by yussufsh** [comment]
/unhold
@sajauddin I am going to merge this for now.
Please see if we can improve the `grep` command to not display versions other than the intended as shown in https://github.com/ocp-power-automation/openshift-install-power/pull/187#issuecomment-1001842829. You can also create an issue for you on this repo.

**Review by yussufsh — APPROVED** [review]

**Pull request merged**
