### PR TITLE
Use latest Terraform and change power path

### PR DESCRIPTION
**Pull request by yussufsh**
Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

### CODE REVIEW

**Comment by yussufsh** [comment]
@aishwaryabk can you please help me running this change on a ppc64le machine? Need to validate cluster deployment works fine with latest Terraform.

**Review by aishwaryabk — DISMISSED** [review]
/lgtm

**Comment by yussufsh** [comment]
@aishwaryabk Thanks for testing this change and reporting the issue with Terraform output with newer versions.

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
@Prajyot-Parab please help with the review.

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
@Prajyot-Parab please help with the review again.

I have figured out the error on macos target is due to rate limiter on GH APIs. We might want to optionally use GH tokens in future. This should not be an issue on a client system as we have limit of 60 hits/hour.
image

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Pull request merged**
