### PR TITLE
Support running on macOS Monterey and Ubuntu 22.04

### PR DESCRIPTION
**Pull request by yussufsh**
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>

### CODE REVIEW

**Review by Prajyot-Parab — DISMISSED** [review]
/lgtm

**Review by sajauddin — DISMISSED** [review]
/lgtm

**Comment by yussufsh** [comment]
> /unhold

@mkumatag could you please check?

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
time being merging this manually.

**Pull request merged**
